/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: sanity/extract.json
export type BrandReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "brand";
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type CategoryReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "category";
};

export type Product = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: number;
  discountPercentage?: number;
  isOnSale?: boolean;
  stock?: number;
  tags?: Array<"Best Seller" | "New Arrival" | "Preorder" | "Coming Soon">;
  variants?: Array<{
    size?: string;
    price?: number;
    stock?: number;
    _key: string;
  }>;
  brand?: BrandReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
};

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h1" | "h2" | "h3" | "h4" | "blockquote";
      listItem?: "bullet";
      markDefs?: Array<{
        href?: string;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: SanityImageAssetReference;
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      alt?: string;
      _type: "image";
      _key: string;
    }
>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Category = {
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | BrandReference
  | SanityImageAssetReference
  | CategoryReference
  | Product
  | BlockContent
  | SanityImageCrop
  | SanityImageHotspot
  | Brand
  | Slug
  | Category
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;

// Source: sanity/lib/queries.ts
// Variable: getProductBySearchQuery
// Query: *[_type == "product" && name match $search] | order(_createdAt desc)
export type GetProductBySearchQueryResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: number;
  discountPercentage?: number;
  isOnSale?: boolean;
  stock?: number;
  tags?: Array<"Best Seller" | "Coming Soon" | "New Arrival" | "Preorder">;
  variants?: Array<{
    size?: string;
    price?: number;
    stock?: number;
    _key: string;
  }>;
  brand?: BrandReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
}>;

// Source: sanity/lib/queries.ts
// Variable: getProductsByCategoryQuery
// Query: *[_type == "product" && $category in categories[]->slug.current] | order(_createdAt desc)
export type GetProductsByCategoryQueryResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: number;
  discountPercentage?: number;
  isOnSale?: boolean;
  stock?: number;
  tags?: Array<"Best Seller" | "Coming Soon" | "New Arrival" | "Preorder">;
  variants?: Array<{
    size?: string;
    price?: number;
    stock?: number;
    _key: string;
  }>;
  brand?: BrandReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
}>;

// Source: sanity/lib/queries.ts
// Variable: getCategoryQuery
// Query: *[_type == "category"]
export type GetCategoryQueryResult = Array<{
  _id: string;
  _type: "category";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  description?: string;
}>;

// Source: sanity/lib/queries.ts
// Variable: getProductsByPageQuery
// Query: *[_type == "product"]   | order(_createdAt desc)[$start...$end]
export type GetProductsByPageQueryResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: number;
  discountPercentage?: number;
  isOnSale?: boolean;
  stock?: number;
  tags?: Array<"Best Seller" | "Coming Soon" | "New Arrival" | "Preorder">;
  variants?: Array<{
    size?: string;
    price?: number;
    stock?: number;
    _key: string;
  }>;
  brand?: BrandReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
}>;

// Source: sanity/lib/queries.ts
// Variable: getProductByIdQuery
// Query: *[_type == "product" && _id == $id][0]
export type GetProductByIdQueryResult = {
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: number;
  discountPercentage?: number;
  isOnSale?: boolean;
  stock?: number;
  tags?: Array<"Best Seller" | "Coming Soon" | "New Arrival" | "Preorder">;
  variants?: Array<{
    size?: string;
    price?: number;
    stock?: number;
    _key: string;
  }>;
  brand?: BrandReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
} | null;

// Source: sanity/lib/queries.ts
// Variable: bestSellersQuery
// Query: *[_type == "product" && "Best Seller" in tags]
export type BestSellersQueryResult = Array<{
  _id: string;
  _type: "product";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: number;
  discountPercentage?: number;
  isOnSale?: boolean;
  stock?: number;
  tags?: Array<"Best Seller" | "Coming Soon" | "New Arrival" | "Preorder">;
  variants?: Array<{
    size?: string;
    price?: number;
    stock?: number;
    _key: string;
  }>;
  brand?: BrandReference;
  mainImage?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    alt?: string;
    _type: "image";
  };
  categories?: Array<
    {
      _key: string;
    } & CategoryReference
  >;
  publishedAt?: string;
  body?: BlockContent;
}>;

// Source: sanity/lib/queries.ts
// Variable: getBrandsQuery
// Query: *[_type == "brand"]
export type GetBrandsQueryResult = Array<{
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  logo?: {
    asset?: SanityImageAssetReference;
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  description?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal";
    listItem?: never;
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
}>;

// Source: sanity/lib/queries.ts
// Variable: getProductsWithCountQuery
// Query: {  "products": *[_type == "product"] | order(_createdAt desc)[$start...$end]{    _id,    name,    price,    image  },  "total": count(*[_type == "product"])}
export type GetProductsWithCountQueryResult = {
  products: Array<{
    _id: string;
    name: string | null;
    price: number | null;
    image: null;
  }>;
  total: number;
};

// Source: sanity/lib/queries.ts
// Variable: getTotal
// Query: count(*[_type == "product"])
export type GetTotalResult = number;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    '\n *[_type == "product" && name match $search] | order(_createdAt desc)': GetProductBySearchQueryResult;
    '\n  *[_type == "product" && $category in categories[]->slug.current] | order(_createdAt desc) \n': GetProductsByCategoryQueryResult;
    '\n  *[_type == "category"]\n': GetCategoryQueryResult;
    '\n  *[_type == "product"] \n  | order(_createdAt desc)[$start...$end]\n': GetProductsByPageQueryResult;
    '\n  *[_type == "product" && _id == $id][0]\n': GetProductByIdQueryResult;
    '\n  *[_type == "product" && "Best Seller" in tags]\n': BestSellersQueryResult;
    '\n*[_type == "brand"]\n': GetBrandsQueryResult;
    '{\n\n  "products": *[_type == "product"] | order(_createdAt desc)[$start...$end]{\n    _id,\n    name,\n    price,\n    image\n  },\n  "total": count(*[_type == "product"])\n}\n\n\n': GetProductsWithCountQueryResult;
    '\ncount(*[_type == "product"])\n': GetTotalResult;
  }
}
